// スタート画面で言語をタップしたときに表示する説明 (短い言葉で項目ごと)
window.HW_LANG_INFO = {
  python: {
    year: '1991', country: 'オランダ', creator: 'グイド・ヴァンロッサム',
    type: 'インタプリタ / 動的型付け',
    strengths: '読みやすい・ライブラリが豊富',
    uses: 'AI、データ分析、Web、自動化',
    style: 'インデントでブロック、; 不要',
    trivia: '名前の由来は英国のコメディ番組',
  },
  java: {
    year: '1995', country: 'アメリカ', creator: 'ジェームズ・ゴスリン',
    type: 'コンパイル / 静的型付け',
    strengths: 'どこでも動く・大規模開発向き',
    uses: '業務システム、Android、マイクラ',
    style: '全部クラスの中、型を明示、; 必須',
    trivia: 'もとは家電を動かすための言語',
  },
  c: {
    year: '1972', country: 'アメリカ', creator: 'デニス・リッチー',
    type: 'コンパイル / 静的型付け',
    strengths: '超高速・ハードを直接操作',
    uses: 'OS、家電・車の組み込み機器',
    style: 'main 関数から開始、; 必須',
    trivia: 'OS の UNIX を書くために誕生',
  },
  cpp: {
    year: '1985', country: 'アメリカ', creator: 'ビャーネ・ストロヴストルップ',
    type: 'コンパイル / 静的型付け',
    strengths: 'C の速さ＋クラスで整理',
    uses: 'ゲームエンジン、ブラウザ、金融',
    style: 'C とほぼ同じ、std:: で標準機能',
    trivia: '++ は「C の次」という意味',
  },
  javascript: {
    year: '1995', country: 'アメリカ', creator: 'ブレンダン・アイク',
    type: 'インタプリタ / 動的型付け',
    strengths: 'ブラウザで動く唯一の言語',
    uses: 'Web サイト、Web アプリ、サーバー',
    style: '型を書かない、; は省略可',
    trivia: '最初の版は約 10 日で完成',
  },
  ruby: {
    year: '1995', country: '日本', creator: 'まつもとゆきひろ',
    type: 'インタプリタ / 動的型付け',
    strengths: '簡潔で書いていて楽しい',
    uses: 'Web サービス（GitHub など）',
    style: 'end で閉じる、( ) 省略可',
    trivia: '日本発で初めて国際規格に',
  },
  go: {
    year: '2009', country: 'アメリカ', creator: 'Google',
    type: 'コンパイル / 静的型付け',
    strengths: 'シンプル・高速・並行処理',
    uses: 'クラウド、Docker、Kubernetes',
    style: 'package を宣言、未使用はエラー',
    trivia: 'マスコットはホリネズミの Gopher',
  },
  rust: {
    year: '2015', country: 'アメリカ', creator: 'Mozilla',
    type: 'コンパイル / 静的型付け',
    strengths: '高速なのにメモリ安全',
    uses: 'OS、ブラウザ、WebAssembly',
    style: 'fn で関数、変数は標準で変更不可',
    trivia: '「最も愛される言語」の常連',
  },
  php: {
    year: '1995', country: 'カナダ', creator: 'ラスマス・ラードフ',
    type: 'インタプリタ / 動的型付け',
    strengths: 'HTML に埋め込める・どこでも動く',
    uses: 'WordPress、Wikipedia',
    style: '変数は $ で始める、連結は .',
    trivia: '元の名前は Personal Home Page',
  },
};
